baseurl: "https://rzy0901.github.io"
languageCode: "en-us"
title: "Ren Zhenyu's website"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    #- name: CV
    #  url: "cv.pdf"
    - name: Subscribe
      url: "index.xml"

params:
  description: "A website built through Hugo and blogdown."
  footer: "Copyright &copy; [Ren Zhenyu](https://rzy0901.github.io) | [Github](https://github.com/rzy0901) | [MAIL](mailto:11812214@mail.sustech.edu.cn)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
